// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrix.proto

package gprotomatrix;

public final class Matrix {
  private Matrix() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gprotomatrix_InMatrices_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gprotomatrix_InMatrices_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gprotomatrix_OutMatrix_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gprotomatrix_OutMatrix_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014matrix.proto\022\014gprotomatrix\"N\n\nInMatric" +
      "es\022\014\n\004rows\030\001 \001(\005\022\014\n\004cols\030\002 \001(\005\022\021\n\tmat1_d" +
      "ata\030\003 \003(\005\022\021\n\tmat2_data\030\004 \003(\005\"5\n\tOutMatri" +
      "x\022\014\n\004rows\030\001 \001(\005\022\014\n\004cols\030\002 \001(\005\022\014\n\004data\030\003 " +
      "\003(\0052\211\001\n\nOperations\022:\n\003Add\022\030.gprotomatrix" +
      ".InMatrices\032\027.gprotomatrix.OutMatrix\"\000\022?" +
      "\n\010Multiply\022\030.gprotomatrix.InMatrices\032\027.g" +
      "protomatrix.OutMatrix\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gprotomatrix_InMatrices_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gprotomatrix_InMatrices_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gprotomatrix_InMatrices_descriptor,
        new java.lang.String[] { "Rows", "Cols", "Mat1Data", "Mat2Data", });
    internal_static_gprotomatrix_OutMatrix_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gprotomatrix_OutMatrix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gprotomatrix_OutMatrix_descriptor,
        new java.lang.String[] { "Rows", "Cols", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
