// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrix.proto

package gprotomatrix;

/**
 * Protobuf type {@code gprotomatrix.OutMatrix}
 */
public  final class OutMatrix extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gprotomatrix.OutMatrix)
    OutMatrixOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OutMatrix.newBuilder() to construct.
  private OutMatrix(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OutMatrix() {
    rows_ = 0;
    cols_ = 0;
    data_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OutMatrix(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            rows_ = input.readInt32();
            break;
          }
          case 16: {

            cols_ = input.readInt32();
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              data_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            data_.add(input.readInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              data_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              data_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        data_ = java.util.Collections.unmodifiableList(data_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gprotomatrix.Matrix.internal_static_gprotomatrix_OutMatrix_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gprotomatrix.Matrix.internal_static_gprotomatrix_OutMatrix_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gprotomatrix.OutMatrix.class, gprotomatrix.OutMatrix.Builder.class);
  }

  private int bitField0_;
  public static final int ROWS_FIELD_NUMBER = 1;
  private int rows_;
  /**
   * <code>int32 rows = 1;</code>
   */
  public int getRows() {
    return rows_;
  }

  public static final int COLS_FIELD_NUMBER = 2;
  private int cols_;
  /**
   * <code>int32 cols = 2;</code>
   */
  public int getCols() {
    return cols_;
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Integer> data_;
  /**
   * <pre>
   *repeated double data = 3;
   * </pre>
   *
   * <code>repeated int32 data = 3;</code>
   */
  public java.util.List<java.lang.Integer>
      getDataList() {
    return data_;
  }
  /**
   * <pre>
   *repeated double data = 3;
   * </pre>
   *
   * <code>repeated int32 data = 3;</code>
   */
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <pre>
   *repeated double data = 3;
   * </pre>
   *
   * <code>repeated int32 data = 3;</code>
   */
  public int getData(int index) {
    return data_.get(index);
  }
  private int dataMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (rows_ != 0) {
      output.writeInt32(1, rows_);
    }
    if (cols_ != 0) {
      output.writeInt32(2, cols_);
    }
    if (getDataList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(dataMemoizedSerializedSize);
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeInt32NoTag(data_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rows_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rows_);
    }
    if (cols_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, cols_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < data_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(data_.get(i));
      }
      size += dataSize;
      if (!getDataList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      dataMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gprotomatrix.OutMatrix)) {
      return super.equals(obj);
    }
    gprotomatrix.OutMatrix other = (gprotomatrix.OutMatrix) obj;

    boolean result = true;
    result = result && (getRows()
        == other.getRows());
    result = result && (getCols()
        == other.getCols());
    result = result && getDataList()
        .equals(other.getDataList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROWS_FIELD_NUMBER;
    hash = (53 * hash) + getRows();
    hash = (37 * hash) + COLS_FIELD_NUMBER;
    hash = (53 * hash) + getCols();
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gprotomatrix.OutMatrix parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gprotomatrix.OutMatrix parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gprotomatrix.OutMatrix parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gprotomatrix.OutMatrix parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gprotomatrix.OutMatrix parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gprotomatrix.OutMatrix parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gprotomatrix.OutMatrix parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gprotomatrix.OutMatrix parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gprotomatrix.OutMatrix parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gprotomatrix.OutMatrix parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gprotomatrix.OutMatrix parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gprotomatrix.OutMatrix parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gprotomatrix.OutMatrix prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gprotomatrix.OutMatrix}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gprotomatrix.OutMatrix)
      gprotomatrix.OutMatrixOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gprotomatrix.Matrix.internal_static_gprotomatrix_OutMatrix_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gprotomatrix.Matrix.internal_static_gprotomatrix_OutMatrix_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gprotomatrix.OutMatrix.class, gprotomatrix.OutMatrix.Builder.class);
    }

    // Construct using gprotomatrix.OutMatrix.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      rows_ = 0;

      cols_ = 0;

      data_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gprotomatrix.Matrix.internal_static_gprotomatrix_OutMatrix_descriptor;
    }

    @java.lang.Override
    public gprotomatrix.OutMatrix getDefaultInstanceForType() {
      return gprotomatrix.OutMatrix.getDefaultInstance();
    }

    @java.lang.Override
    public gprotomatrix.OutMatrix build() {
      gprotomatrix.OutMatrix result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gprotomatrix.OutMatrix buildPartial() {
      gprotomatrix.OutMatrix result = new gprotomatrix.OutMatrix(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.rows_ = rows_;
      result.cols_ = cols_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        data_ = java.util.Collections.unmodifiableList(data_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.data_ = data_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gprotomatrix.OutMatrix) {
        return mergeFrom((gprotomatrix.OutMatrix)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gprotomatrix.OutMatrix other) {
      if (other == gprotomatrix.OutMatrix.getDefaultInstance()) return this;
      if (other.getRows() != 0) {
        setRows(other.getRows());
      }
      if (other.getCols() != 0) {
        setCols(other.getCols());
      }
      if (!other.data_.isEmpty()) {
        if (data_.isEmpty()) {
          data_ = other.data_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureDataIsMutable();
          data_.addAll(other.data_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gprotomatrix.OutMatrix parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gprotomatrix.OutMatrix) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int rows_ ;
    /**
     * <code>int32 rows = 1;</code>
     */
    public int getRows() {
      return rows_;
    }
    /**
     * <code>int32 rows = 1;</code>
     */
    public Builder setRows(int value) {
      
      rows_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rows = 1;</code>
     */
    public Builder clearRows() {
      
      rows_ = 0;
      onChanged();
      return this;
    }

    private int cols_ ;
    /**
     * <code>int32 cols = 2;</code>
     */
    public int getCols() {
      return cols_;
    }
    /**
     * <code>int32 cols = 2;</code>
     */
    public Builder setCols(int value) {
      
      cols_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cols = 2;</code>
     */
    public Builder clearCols() {
      
      cols_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> data_ = java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        data_ = new java.util.ArrayList<java.lang.Integer>(data_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     *repeated double data = 3;
     * </pre>
     *
     * <code>repeated int32 data = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getDataList() {
      return java.util.Collections.unmodifiableList(data_);
    }
    /**
     * <pre>
     *repeated double data = 3;
     * </pre>
     *
     * <code>repeated int32 data = 3;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <pre>
     *repeated double data = 3;
     * </pre>
     *
     * <code>repeated int32 data = 3;</code>
     */
    public int getData(int index) {
      return data_.get(index);
    }
    /**
     * <pre>
     *repeated double data = 3;
     * </pre>
     *
     * <code>repeated int32 data = 3;</code>
     */
    public Builder setData(
        int index, int value) {
      ensureDataIsMutable();
      data_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *repeated double data = 3;
     * </pre>
     *
     * <code>repeated int32 data = 3;</code>
     */
    public Builder addData(int value) {
      ensureDataIsMutable();
      data_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *repeated double data = 3;
     * </pre>
     *
     * <code>repeated int32 data = 3;</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureDataIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, data_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *repeated double data = 3;
     * </pre>
     *
     * <code>repeated int32 data = 3;</code>
     */
    public Builder clearData() {
      data_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gprotomatrix.OutMatrix)
  }

  // @@protoc_insertion_point(class_scope:gprotomatrix.OutMatrix)
  private static final gprotomatrix.OutMatrix DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gprotomatrix.OutMatrix();
  }

  public static gprotomatrix.OutMatrix getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OutMatrix>
      PARSER = new com.google.protobuf.AbstractParser<OutMatrix>() {
    @java.lang.Override
    public OutMatrix parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OutMatrix(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OutMatrix> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OutMatrix> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gprotomatrix.OutMatrix getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

