// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrix.proto

package gprotomatrix;

public interface OutMatrixOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gprotomatrix.OutMatrix)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rows = 1;</code>
   */
  int getRows();

  /**
   * <code>int32 cols = 2;</code>
   */
  int getCols();

  /**
   * <pre>
   *repeated double data = 3;
   * </pre>
   *
   * <code>repeated int32 data = 3;</code>
   */
  java.util.List<java.lang.Integer> getDataList();
  /**
   * <pre>
   *repeated double data = 3;
   * </pre>
   *
   * <code>repeated int32 data = 3;</code>
   */
  int getDataCount();
  /**
   * <pre>
   *repeated double data = 3;
   * </pre>
   *
   * <code>repeated int32 data = 3;</code>
   */
  int getData(int index);
}
