# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matrix.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='matrix.proto',
  package='gprotomatrix',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cmatrix.proto\x12\x0cgprotomatrix\"N\n\nInMatrices\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x02 \x01(\x05\x12\x11\n\tmat1_data\x18\x03 \x03(\x05\x12\x11\n\tmat2_data\x18\x04 \x03(\x05\"5\n\tOutMatrix\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x05\x32\x89\x01\n\nOperations\x12:\n\x03\x41\x64\x64\x12\x18.gprotomatrix.InMatrices\x1a\x17.gprotomatrix.OutMatrix\"\x00\x12?\n\x08Multiply\x12\x18.gprotomatrix.InMatrices\x1a\x17.gprotomatrix.OutMatrix\"\x00\x62\x06proto3'
)




_INMATRICES = _descriptor.Descriptor(
  name='InMatrices',
  full_name='gprotomatrix.InMatrices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='gprotomatrix.InMatrices.rows', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cols', full_name='gprotomatrix.InMatrices.cols', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mat1_data', full_name='gprotomatrix.InMatrices.mat1_data', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mat2_data', full_name='gprotomatrix.InMatrices.mat2_data', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=108,
)


_OUTMATRIX = _descriptor.Descriptor(
  name='OutMatrix',
  full_name='gprotomatrix.OutMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='gprotomatrix.OutMatrix.rows', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cols', full_name='gprotomatrix.OutMatrix.cols', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='gprotomatrix.OutMatrix.data', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['InMatrices'] = _INMATRICES
DESCRIPTOR.message_types_by_name['OutMatrix'] = _OUTMATRIX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InMatrices = _reflection.GeneratedProtocolMessageType('InMatrices', (_message.Message,), {
  'DESCRIPTOR' : _INMATRICES,
  '__module__' : 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:gprotomatrix.InMatrices)
  })
_sym_db.RegisterMessage(InMatrices)

OutMatrix = _reflection.GeneratedProtocolMessageType('OutMatrix', (_message.Message,), {
  'DESCRIPTOR' : _OUTMATRIX,
  '__module__' : 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:gprotomatrix.OutMatrix)
  })
_sym_db.RegisterMessage(OutMatrix)



_OPERATIONS = _descriptor.ServiceDescriptor(
  name='Operations',
  full_name='gprotomatrix.Operations',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=166,
  serialized_end=303,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='gprotomatrix.Operations.Add',
    index=0,
    containing_service=None,
    input_type=_INMATRICES,
    output_type=_OUTMATRIX,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Multiply',
    full_name='gprotomatrix.Operations.Multiply',
    index=1,
    containing_service=None,
    input_type=_INMATRICES,
    output_type=_OUTMATRIX,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPERATIONS)

DESCRIPTOR.services_by_name['Operations'] = _OPERATIONS

# @@protoc_insertion_point(module_scope)
