# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import matrix_pb2 as matrix__pb2


class OperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/gprotomatrix.Operations/Add',
                request_serializer=matrix__pb2.InMatrices.SerializeToString,
                response_deserializer=matrix__pb2.OutMatrix.FromString,
                )
        self.Multiply = channel.unary_unary(
                '/gprotomatrix.Operations/Multiply',
                request_serializer=matrix__pb2.InMatrices.SerializeToString,
                response_deserializer=matrix__pb2.OutMatrix.FromString,
                )


class OperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=matrix__pb2.InMatrices.FromString,
                    response_serializer=matrix__pb2.OutMatrix.SerializeToString,
            ),
            'Multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiply,
                    request_deserializer=matrix__pb2.InMatrices.FromString,
                    response_serializer=matrix__pb2.OutMatrix.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gprotomatrix.Operations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Operations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gprotomatrix.Operations/Add',
            matrix__pb2.InMatrices.SerializeToString,
            matrix__pb2.OutMatrix.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gprotomatrix.Operations/Multiply',
            matrix__pb2.InMatrices.SerializeToString,
            matrix__pb2.OutMatrix.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
