// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrix.proto

package gproto_matrix;

public interface InMatricesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gproto_matrix.InMatrices)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rows = 1;</code>
   */
  int getRows();

  /**
   * <code>int32 cols = 2;</code>
   */
  int getCols();

  /**
   * <code>repeated int32 mat1_data = 3;</code>
   */
  java.util.List<java.lang.Integer> getMat1DataList();
  /**
   * <code>repeated int32 mat1_data = 3;</code>
   */
  int getMat1DataCount();
  /**
   * <code>repeated int32 mat1_data = 3;</code>
   */
  int getMat1Data(int index);

  /**
   * <pre>
   *repeated double mat1_data = 3;
   *repeated double mat2_data = 4;
   * </pre>
   *
   * <code>repeated int32 mat2_data = 4;</code>
   */
  java.util.List<java.lang.Integer> getMat2DataList();
  /**
   * <pre>
   *repeated double mat1_data = 3;
   *repeated double mat2_data = 4;
   * </pre>
   *
   * <code>repeated int32 mat2_data = 4;</code>
   */
  int getMat2DataCount();
  /**
   * <pre>
   *repeated double mat1_data = 3;
   *repeated double mat2_data = 4;
   * </pre>
   *
   * <code>repeated int32 mat2_data = 4;</code>
   */
  int getMat2Data(int index);
}
