// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrix.proto

package gproto_matrix;

/**
 * Protobuf type {@code gproto_matrix.InMatrices}
 */
public  final class InMatrices extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gproto_matrix.InMatrices)
    InMatricesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InMatrices.newBuilder() to construct.
  private InMatrices(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InMatrices() {
    rows_ = 0;
    cols_ = 0;
    mat1Data_ = java.util.Collections.emptyList();
    mat2Data_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InMatrices(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            rows_ = input.readInt32();
            break;
          }
          case 16: {

            cols_ = input.readInt32();
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              mat1Data_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            mat1Data_.add(input.readInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              mat1Data_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              mat1Data_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              mat2Data_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000008;
            }
            mat2Data_.add(input.readInt32());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
              mat2Data_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000008;
            }
            while (input.getBytesUntilLimit() > 0) {
              mat2Data_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        mat1Data_ = java.util.Collections.unmodifiableList(mat1Data_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        mat2Data_ = java.util.Collections.unmodifiableList(mat2Data_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gproto_matrix.Matrix.internal_static_gproto_matrix_InMatrices_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gproto_matrix.Matrix.internal_static_gproto_matrix_InMatrices_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gproto_matrix.InMatrices.class, gproto_matrix.InMatrices.Builder.class);
  }

  private int bitField0_;
  public static final int ROWS_FIELD_NUMBER = 1;
  private int rows_;
  /**
   * <code>int32 rows = 1;</code>
   */
  public int getRows() {
    return rows_;
  }

  public static final int COLS_FIELD_NUMBER = 2;
  private int cols_;
  /**
   * <code>int32 cols = 2;</code>
   */
  public int getCols() {
    return cols_;
  }

  public static final int MAT1_DATA_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Integer> mat1Data_;
  /**
   * <code>repeated int32 mat1_data = 3;</code>
   */
  public java.util.List<java.lang.Integer>
      getMat1DataList() {
    return mat1Data_;
  }
  /**
   * <code>repeated int32 mat1_data = 3;</code>
   */
  public int getMat1DataCount() {
    return mat1Data_.size();
  }
  /**
   * <code>repeated int32 mat1_data = 3;</code>
   */
  public int getMat1Data(int index) {
    return mat1Data_.get(index);
  }
  private int mat1DataMemoizedSerializedSize = -1;

  public static final int MAT2_DATA_FIELD_NUMBER = 4;
  private java.util.List<java.lang.Integer> mat2Data_;
  /**
   * <pre>
   *repeated double mat1_data = 3;
   *repeated double mat2_data = 4;
   * </pre>
   *
   * <code>repeated int32 mat2_data = 4;</code>
   */
  public java.util.List<java.lang.Integer>
      getMat2DataList() {
    return mat2Data_;
  }
  /**
   * <pre>
   *repeated double mat1_data = 3;
   *repeated double mat2_data = 4;
   * </pre>
   *
   * <code>repeated int32 mat2_data = 4;</code>
   */
  public int getMat2DataCount() {
    return mat2Data_.size();
  }
  /**
   * <pre>
   *repeated double mat1_data = 3;
   *repeated double mat2_data = 4;
   * </pre>
   *
   * <code>repeated int32 mat2_data = 4;</code>
   */
  public int getMat2Data(int index) {
    return mat2Data_.get(index);
  }
  private int mat2DataMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (rows_ != 0) {
      output.writeInt32(1, rows_);
    }
    if (cols_ != 0) {
      output.writeInt32(2, cols_);
    }
    if (getMat1DataList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(mat1DataMemoizedSerializedSize);
    }
    for (int i = 0; i < mat1Data_.size(); i++) {
      output.writeInt32NoTag(mat1Data_.get(i));
    }
    if (getMat2DataList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(mat2DataMemoizedSerializedSize);
    }
    for (int i = 0; i < mat2Data_.size(); i++) {
      output.writeInt32NoTag(mat2Data_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rows_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rows_);
    }
    if (cols_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, cols_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < mat1Data_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(mat1Data_.get(i));
      }
      size += dataSize;
      if (!getMat1DataList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      mat1DataMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < mat2Data_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(mat2Data_.get(i));
      }
      size += dataSize;
      if (!getMat2DataList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      mat2DataMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gproto_matrix.InMatrices)) {
      return super.equals(obj);
    }
    gproto_matrix.InMatrices other = (gproto_matrix.InMatrices) obj;

    boolean result = true;
    result = result && (getRows()
        == other.getRows());
    result = result && (getCols()
        == other.getCols());
    result = result && getMat1DataList()
        .equals(other.getMat1DataList());
    result = result && getMat2DataList()
        .equals(other.getMat2DataList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROWS_FIELD_NUMBER;
    hash = (53 * hash) + getRows();
    hash = (37 * hash) + COLS_FIELD_NUMBER;
    hash = (53 * hash) + getCols();
    if (getMat1DataCount() > 0) {
      hash = (37 * hash) + MAT1_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getMat1DataList().hashCode();
    }
    if (getMat2DataCount() > 0) {
      hash = (37 * hash) + MAT2_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getMat2DataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gproto_matrix.InMatrices parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gproto_matrix.InMatrices parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gproto_matrix.InMatrices parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gproto_matrix.InMatrices parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gproto_matrix.InMatrices parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gproto_matrix.InMatrices parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gproto_matrix.InMatrices parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gproto_matrix.InMatrices parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gproto_matrix.InMatrices parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gproto_matrix.InMatrices parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gproto_matrix.InMatrices parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gproto_matrix.InMatrices parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gproto_matrix.InMatrices prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gproto_matrix.InMatrices}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gproto_matrix.InMatrices)
      gproto_matrix.InMatricesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gproto_matrix.Matrix.internal_static_gproto_matrix_InMatrices_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gproto_matrix.Matrix.internal_static_gproto_matrix_InMatrices_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gproto_matrix.InMatrices.class, gproto_matrix.InMatrices.Builder.class);
    }

    // Construct using gproto_matrix.InMatrices.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      rows_ = 0;

      cols_ = 0;

      mat1Data_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      mat2Data_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gproto_matrix.Matrix.internal_static_gproto_matrix_InMatrices_descriptor;
    }

    @java.lang.Override
    public gproto_matrix.InMatrices getDefaultInstanceForType() {
      return gproto_matrix.InMatrices.getDefaultInstance();
    }

    @java.lang.Override
    public gproto_matrix.InMatrices build() {
      gproto_matrix.InMatrices result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gproto_matrix.InMatrices buildPartial() {
      gproto_matrix.InMatrices result = new gproto_matrix.InMatrices(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.rows_ = rows_;
      result.cols_ = cols_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        mat1Data_ = java.util.Collections.unmodifiableList(mat1Data_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.mat1Data_ = mat1Data_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        mat2Data_ = java.util.Collections.unmodifiableList(mat2Data_);
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.mat2Data_ = mat2Data_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gproto_matrix.InMatrices) {
        return mergeFrom((gproto_matrix.InMatrices)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gproto_matrix.InMatrices other) {
      if (other == gproto_matrix.InMatrices.getDefaultInstance()) return this;
      if (other.getRows() != 0) {
        setRows(other.getRows());
      }
      if (other.getCols() != 0) {
        setCols(other.getCols());
      }
      if (!other.mat1Data_.isEmpty()) {
        if (mat1Data_.isEmpty()) {
          mat1Data_ = other.mat1Data_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureMat1DataIsMutable();
          mat1Data_.addAll(other.mat1Data_);
        }
        onChanged();
      }
      if (!other.mat2Data_.isEmpty()) {
        if (mat2Data_.isEmpty()) {
          mat2Data_ = other.mat2Data_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureMat2DataIsMutable();
          mat2Data_.addAll(other.mat2Data_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gproto_matrix.InMatrices parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gproto_matrix.InMatrices) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int rows_ ;
    /**
     * <code>int32 rows = 1;</code>
     */
    public int getRows() {
      return rows_;
    }
    /**
     * <code>int32 rows = 1;</code>
     */
    public Builder setRows(int value) {
      
      rows_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rows = 1;</code>
     */
    public Builder clearRows() {
      
      rows_ = 0;
      onChanged();
      return this;
    }

    private int cols_ ;
    /**
     * <code>int32 cols = 2;</code>
     */
    public int getCols() {
      return cols_;
    }
    /**
     * <code>int32 cols = 2;</code>
     */
    public Builder setCols(int value) {
      
      cols_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cols = 2;</code>
     */
    public Builder clearCols() {
      
      cols_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> mat1Data_ = java.util.Collections.emptyList();
    private void ensureMat1DataIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        mat1Data_ = new java.util.ArrayList<java.lang.Integer>(mat1Data_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int32 mat1_data = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getMat1DataList() {
      return java.util.Collections.unmodifiableList(mat1Data_);
    }
    /**
     * <code>repeated int32 mat1_data = 3;</code>
     */
    public int getMat1DataCount() {
      return mat1Data_.size();
    }
    /**
     * <code>repeated int32 mat1_data = 3;</code>
     */
    public int getMat1Data(int index) {
      return mat1Data_.get(index);
    }
    /**
     * <code>repeated int32 mat1_data = 3;</code>
     */
    public Builder setMat1Data(
        int index, int value) {
      ensureMat1DataIsMutable();
      mat1Data_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 mat1_data = 3;</code>
     */
    public Builder addMat1Data(int value) {
      ensureMat1DataIsMutable();
      mat1Data_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 mat1_data = 3;</code>
     */
    public Builder addAllMat1Data(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureMat1DataIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, mat1Data_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 mat1_data = 3;</code>
     */
    public Builder clearMat1Data() {
      mat1Data_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> mat2Data_ = java.util.Collections.emptyList();
    private void ensureMat2DataIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        mat2Data_ = new java.util.ArrayList<java.lang.Integer>(mat2Data_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <pre>
     *repeated double mat1_data = 3;
     *repeated double mat2_data = 4;
     * </pre>
     *
     * <code>repeated int32 mat2_data = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getMat2DataList() {
      return java.util.Collections.unmodifiableList(mat2Data_);
    }
    /**
     * <pre>
     *repeated double mat1_data = 3;
     *repeated double mat2_data = 4;
     * </pre>
     *
     * <code>repeated int32 mat2_data = 4;</code>
     */
    public int getMat2DataCount() {
      return mat2Data_.size();
    }
    /**
     * <pre>
     *repeated double mat1_data = 3;
     *repeated double mat2_data = 4;
     * </pre>
     *
     * <code>repeated int32 mat2_data = 4;</code>
     */
    public int getMat2Data(int index) {
      return mat2Data_.get(index);
    }
    /**
     * <pre>
     *repeated double mat1_data = 3;
     *repeated double mat2_data = 4;
     * </pre>
     *
     * <code>repeated int32 mat2_data = 4;</code>
     */
    public Builder setMat2Data(
        int index, int value) {
      ensureMat2DataIsMutable();
      mat2Data_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *repeated double mat1_data = 3;
     *repeated double mat2_data = 4;
     * </pre>
     *
     * <code>repeated int32 mat2_data = 4;</code>
     */
    public Builder addMat2Data(int value) {
      ensureMat2DataIsMutable();
      mat2Data_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *repeated double mat1_data = 3;
     *repeated double mat2_data = 4;
     * </pre>
     *
     * <code>repeated int32 mat2_data = 4;</code>
     */
    public Builder addAllMat2Data(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureMat2DataIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, mat2Data_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *repeated double mat1_data = 3;
     *repeated double mat2_data = 4;
     * </pre>
     *
     * <code>repeated int32 mat2_data = 4;</code>
     */
    public Builder clearMat2Data() {
      mat2Data_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gproto_matrix.InMatrices)
  }

  // @@protoc_insertion_point(class_scope:gproto_matrix.InMatrices)
  private static final gproto_matrix.InMatrices DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gproto_matrix.InMatrices();
  }

  public static gproto_matrix.InMatrices getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InMatrices>
      PARSER = new com.google.protobuf.AbstractParser<InMatrices>() {
    @java.lang.Override
    public InMatrices parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InMatrices(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InMatrices> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InMatrices> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gproto_matrix.InMatrices getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

