// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrix.proto

package gproto_matrix;

public final class Matrix {
  private Matrix() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gproto_matrix_InMatrices_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gproto_matrix_InMatrices_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gproto_matrix_OutMatrix_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gproto_matrix_OutMatrix_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014matrix.proto\022\rgproto_matrix\"N\n\nInMatri" +
      "ces\022\014\n\004rows\030\001 \001(\005\022\014\n\004cols\030\002 \001(\005\022\021\n\tmat1_" +
      "data\030\003 \003(\005\022\021\n\tmat2_data\030\004 \003(\005\"5\n\tOutMatr" +
      "ix\022\014\n\004rows\030\001 \001(\005\022\014\n\004cols\030\002 \001(\005\022\014\n\004data\030\003" +
      " \003(\0052\215\001\n\nOperations\022<\n\003Add\022\031.gproto_matr" +
      "ix.InMatrices\032\030.gproto_matrix.OutMatrix\"" +
      "\000\022A\n\010Multiply\022\031.gproto_matrix.InMatrices" +
      "\032\030.gproto_matrix.OutMatrix\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gproto_matrix_InMatrices_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gproto_matrix_InMatrices_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gproto_matrix_InMatrices_descriptor,
        new java.lang.String[] { "Rows", "Cols", "Mat1Data", "Mat2Data", });
    internal_static_gproto_matrix_OutMatrix_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gproto_matrix_OutMatrix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gproto_matrix_OutMatrix_descriptor,
        new java.lang.String[] { "Rows", "Cols", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
